### ISSUE TITLE
[aseriestodis] Second frame is ignored in palette generation

### ISSUE THREAD

**Issue by MandL27** [Gamer2020/DisassemblyTools#3]
Title. If there's a color used on the second frame but not on the first, it gets set to whatever the nearest first frame color is.

Screenshot:
![image](https://user-images.githubusercontent.com/10366615/146486801-7ffd9574-7ee1-4aa9-8352-eca7b25bc93b.png)

The sprite before insertion (it's under 16 colors; I counted):
![image](https://user-images.githubusercontent.com/10366615/146488743-bf493927-b139-44dd-9818-b8ce4d53b002.png)

**Comment by Gamer2020** [comment]
Able to reproduce. Investigating.

**Comment by Gamer2020** [comment]
Fixed in initial release.

https://github.com/Gamer2020/DisassemblyTools/releases/tag/0.1.0
